import { FormEvent, useMemo, useState } from "react";
import { CrowdCanvas } from "./components/ui/crowd-canvas";
import { crowdSprite, landingContent } from "./data/landing";
import { formatINR, products, type Product } from "./data/products";

type View = "home" | "shop" | "product" | "negotiate" | "cart" | "checkout" | "success" | "merchant" | "deals" | "how" | "dashboard" | "history" | "settings" | "about";
type Deal = { product: Product; price: number };
type Message = { author: "you" | "marchander"; text: string; price?: number };

const steps = ["Browse", "Offer", "Agree", "Checkout"];

export default function App() {
  const [view, setView] = useState<View>("home");
  const [selected, setSelected] = useState(products[0]);
  const [deal, setDeal] = useState<Deal | null>(null);
  const [offer, setOffer] = useState("");
  const [round, setRound] = useState(1);
  const [messages, setMessages] = useState<Message[]>([{ author: "marchander", text: "I can help you find a fair price. What would you like to offer?" }]);
  const [listening, setListening] = useState(false);
  const [saved, setSaved] = useState<string[]>([]);
  const [orderNumber] = useState("MCH-10294");

  const navigate = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const choose = (product: Product, next: View = "product") => { setSelected(product); setMessages([{ author: "marchander", text: "I can help you find a fair price. What would you like to offer?" }]); setOffer(""); setRound(1); navigate(next); };
  const proposedCounter = useMemo(() => Math.max(selected.floor, Math.round((selected.price + selected.floor) / 2 / 100) * 100), [selected]);

  const submitOffer = (event: FormEvent) => {
    event.preventDefault();
    const value = Number(offer.replace(/[^0-9]/g, ""));
    if (!value) return;
    const next: Message[] = [...messages, { author: "you", text: `I'd like to offer ${formatINR(value)}.`, price: value }];
    if (value >= selected.floor) {
      setDeal({ product: selected, price: value });
      setMessages([...next, { author: "marchander", text: "That works. Your offer has been accepted.", price: value }]);
    } else {
      const counter = Math.max(selected.floor, proposedCounter - (round - 1) * 300);
      setMessages([...next, { author: "marchander", text: `I can’t go that low, but I can offer ${formatINR(counter)}.`, price: counter }]);
      setRound((value) => value + 1);
    }
    setOffer("");
  };

  return <main className="app-shell">
    <header className="site-header"><button className="brand" onClick={() => navigate("home")}>MARCHANDER <small>AI</small><span>®</span></button><nav><button onClick={() => navigate("home")}>Home</button><button onClick={() => navigate("shop")}>Marketplace</button><button onClick={() => navigate("how")}>How it works</button><button onClick={() => navigate("negotiate")}>AI Negotiator</button><button onClick={() => navigate("deals")}>Deals</button><button onClick={() => navigate("about")}>About</button></nav><div className="header-actions"><button aria-label="Search">⌕</button><button aria-label="Wishlist" onClick={() => navigate("dashboard")}>♡</button><button className="cart-button" onClick={() => navigate("cart")}>Bag <b>{deal ? "01" : "00"}</b></button><button className="sign-in" onClick={() => navigate("settings")}>Sign in</button><button className="nav-cta" onClick={() => navigate("shop")}>Start negotiating ↗</button></div></header>
    {view === "home" && <Home onStart={() => navigate("shop")} onShop={() => navigate("shop")} />}
    {view === "shop" && <Catalog onChoose={choose} saved={saved} onSave={(id) => setSaved((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])} />}
    {view === "product" && <ProductPage product={selected} onNegotiate={() => navigate("negotiate")} onBack={() => navigate("shop")} />}
    {view === "negotiate" && <Negotiation product={selected} messages={messages} offer={offer} round={round} listening={listening} accepted={deal?.product.id === selected.id} onOffer={setOffer} onSubmit={submitOffer} onListen={() => setListening(!listening)} onAccept={() => setDeal({ product: selected, price: messages[messages.length - 1]?.price ?? proposedCounter })} onCart={() => navigate("cart")} onExit={() => navigate("product")} />}
    {view === "cart" && <Cart deal={deal} onContinue={() => navigate("shop")} onCheckout={() => navigate("checkout")} />}
    {view === "checkout" && <Checkout deal={deal} onDone={() => navigate("success")} />}
    {view === "success" && <OrderSuccess deal={deal} orderNumber={orderNumber} onShop={() => { setDeal(null); navigate("shop"); }} />}
    {view === "deals" && <Deals onChoose={choose} />}
    {view === "how" && <HowItWorks onStart={() => navigate("shop")} />}
    {view === "dashboard" && <Dashboard saved={saved} onHistory={() => navigate("history")} onSettings={() => navigate("settings")} />}
    {view === "history" && <History onNegotiate={() => choose(products[0], "negotiate")} />}
    {view === "settings" && <Settings />}
    {view === "merchant" && <Merchant onShop={() => navigate("shop")} />}
    {view === "about" && <About onHow={() => navigate("how")} />}
  </main>;
}

function Home({ onStart, onShop }: { onStart: () => void; onShop: () => void }) { const c = landingContent; return <><section className="hero"><div className="hero-copy"><p className="eyebrow"><i />{c.eyebrow}</p><h1>{c.headline.map((line) => <span key={line}>{line}</span>)}</h1><p className="description">{c.description}</p><div className="actions"><button className="button button-primary" onClick={onStart}>{c.primaryAction}<span>↗</span></button><button className="button button-secondary" onClick={onShop}>Explore products<span>↓</span></button></div></div><aside className="hero-note"><p>{c.crowdLabel}</p><ul>{c.trust.map((item) => <li key={item}>{item}</li>)}</ul></aside><div className="crowd-wrap"><CrowdCanvas src={crowdSprite} /></div><div className="scroll-cue"><span>NEGOTIATE WITH CLARITY</span><b>↓</b></div></section><section className="how"><p className="eyebrow"><i />How it works</p><h2>A fair deal, without<br />the awkward bit.</h2><div className="step-grid">{["Find something you love.", "Name a price by voice or text.", "Let Marchander work the deal."].map((text, i) => <article key={text}><span>0{i + 1}</span><h3>{text}</h3><p>Clear terms, seller-controlled limits, and no surprises.</p></article>)}</div></section></> }

function Catalog({ onChoose, saved, onSave }: { onChoose: (p: Product, next?: View) => void; saved: string[]; onSave: (id: string) => void }) { return <section className="page catalog"><div className="section-heading"><p className="eyebrow"><i />Marketplace</p><h1>Negotiate your price.</h1><p>Don’t just shop. Make an offer.</p></div><div className="market-tools"><label>⌕ <input placeholder="Search products, brands and categories" /></label><button>🎙 Voice search</button><button>Categories⌄</button><button>Sort: featured⌄</button><button>Filters ⚙</button></div><div className="filters"><button className="active">All products</button><button>Electronics</button><button>Fashion</button><button>Shoes</button><button>Home & living</button><button>Accessories</button><button>Gaming</button></div><div className="product-grid">{products.map((p) => <article className="product-card" key={p.id}><div className="product-image" onClick={() => onChoose(p)}><img src={p.image} alt={p.name} /><span>Negotiable</span><button className="wish" aria-label={`Save ${p.name}`} onClick={(event) => { event.stopPropagation(); onSave(p.id); }}>{saved.includes(p.id) ? "♥" : "♡"}</button></div><p>{p.category} · ★ 4.8 <small>(124)</small></p><h2>{p.name}</h2><div><s>{formatINR(Math.round(p.price * 1.14))}</s><strong>{formatINR(p.price)}</strong><em> 12% off</em></div><div className="card-actions"><button onClick={() => onChoose(p)}>Quick view</button><button onClick={() => onChoose(p, "negotiate")}>Negotiate ↗</button></div></article>)}</div></section> }

function ProductPage({ product, onNegotiate, onBack }: { product: Product; onNegotiate: () => void; onBack: () => void }) { return <section className="page product-page"><button className="back" onClick={onBack}>← Back to shop</button><div className="product-layout"><div className="detail-image"><img src={product.image} alt={product.name} /></div><div className="product-detail"><p className="eyebrow"><i />{product.category}</p><h1>{product.name}</h1><p className="product-price">{formatINR(product.price)}</p><p className="description">{product.description}</p><ul className="specs">{product.specs.map((spec) => <li key={spec}>{spec}</li>)}</ul><div className="deal-panel"><span>Think you can get a better price?</span><button className="button button-primary" onClick={onNegotiate}>Make an offer <b>↗</b></button></div><p className="fine-print">A deal is only added to your bag once both sides agree.</p></div></div></section> }

function Negotiation({ product, messages, offer, round, listening, accepted, onOffer, onSubmit, onListen, onAccept, onCart, onExit }: { product: Product; messages: Message[]; offer: string; round: number; listening: boolean; accepted: boolean; onOffer: (v: string) => void; onSubmit: (e: FormEvent) => void; onListen: () => void; onAccept: () => void; onCart: () => void; onExit: () => void }) { const latest = messages[messages.length - 1]; return <section className="page negotiation"><div className="neg-top"><button className="back" onClick={onExit}>← Leave negotiation</button><div className="rounds">{steps.map((s, i) => <span className={i < 2 || accepted ? "done" : ""} key={s}>{i + 1}. {s}</span>)}</div></div><div className="neg-layout"><aside className="neg-product"><img src={product.image} alt="" /><p>{product.category}</p><h2>{product.name}</h2><div className="price-line"><span>Listed price</span><strong>{formatINR(product.price)}</strong></div><div className="price-line current"><span>Your current offer</span><strong>{latest?.author === "you" && latest.price ? formatINR(latest.price) : "—"}</strong></div></aside><div className="conversation"><div className="conversation-header"><div><p className="eyebrow"><i />Live negotiation</p><h1>{accepted ? "Deal accepted." : "Let’s find a price."}</h1></div><span className={`status ${listening ? "listening" : ""}`}>{listening ? "Listening" : accepted ? "Accepted" : `Round ${round} of 4`}</span></div><div className="messages">{messages.map((m, i) => <div className={`message ${m.author}`} key={i}><span>{m.author === "you" ? "You" : "Marchander AI"}</span><p>{m.text}</p></div>)}</div>{accepted ? <div className="accepted-panel"><p>Your agreed price</p><h2>{formatINR(latest?.price ?? product.price)}</h2><button className="button button-primary" onClick={onCart}>Add deal to bag <b>→</b></button></div> : <form className="offer-form" onSubmit={onSubmit}><label htmlFor="offer">Make an offer</label><div><span>₹</span><input id="offer" value={offer} onChange={(e) => onOffer(e.target.value)} placeholder="Enter your price" inputMode="numeric" /><button type="submit">Send ↗</button></div><button type="button" className={`mic ${listening ? "is-listening" : ""}`} onClick={onListen}>◉ {listening ? "Listening… tap to stop" : "Use your voice instead"}</button></form>} {!accepted && latest?.author === "marchander" && messages.length > 1 && <button className="accept-counter" onClick={onAccept}>Accept {latest.price ? formatINR(latest.price) : "counter offer"}</button>}</div></div></section> }

function Cart({ deal, onContinue, onCheckout }: { deal: Deal | null; onContinue: () => void; onCheckout: () => void }) { return <section className="page cart-page"><p className="eyebrow"><i />Your bag</p><h1>{deal ? "One good deal." : "Your bag is empty."}</h1>{deal ? <div className="cart-layout"><article className="cart-item"><img src={deal.product.image} alt="" /><div><p>{deal.product.category}</p><h2>{deal.product.name}</h2><span>Agreed price <strong>{formatINR(deal.price)}</strong></span></div></article><aside className="summary"><h2>Order summary</h2><p><span>Negotiated price</span><b>{formatINR(deal.price)}</b></p><p><span>Delivery</span><b>Free</b></p><hr /><p className="total"><span>Total</span><b>{formatINR(deal.price)}</b></p><button className="button button-primary" onClick={onCheckout}>Secure checkout →</button></aside></div> : <button className="button button-primary" onClick={onContinue}>Explore products →</button>}</section> }

function Checkout({ deal, onDone }: { deal: Deal | null; onDone: () => void }) { return <section className="page checkout"><div className="checkout-card"><p className="eyebrow"><i />Secure checkout</p><h1>Almost yours.</h1><p className="description">This demo preserves your negotiated price through checkout.</p><div className="checkout-total"><span>Amount due</span><strong>{deal ? formatINR(deal.price) : "₹0"}</strong></div><label>Name<input placeholder="Your name" /></label><label>Delivery address<input placeholder="Street, city, PIN code" /></label><button className="button button-primary" onClick={onDone}>Place demo order →</button><p className="fine-print">No payment is collected in this prototype.</p></div></section> }

function Merchant({ onShop }: { onShop: () => void }) { return <section className="page merchant"><p className="eyebrow"><i />Merchant space</p><div className="merchant-head"><h1>Set the floor.<br /><span>Keep the conversation.</span></h1><p>Marchander gives you guardrails, not guesswork. Every accepted deal stays inside the price you control.</p><button className="button button-primary" onClick={onShop}>View buyer experience ↗</button></div><div className="metrics"><article><span>₹4.2L</span><p>Negotiated GMV</p><em>↑ 18% this month</em></article><article><span>68%</span><p>Offer-to-deal rate</p><em>↑ 6% this month</em></article><article><span>3.1</span><p>Average rounds</p><em>Clear, quick outcomes</em></article></div><div className="merchant-table"><div><h2>Live products</h2><button>+ Add product</button></div>{products.slice(0, 3).map((p) => <article key={p.id}><span>{p.name}</span><span>List {formatINR(p.price)}</span><span>Floor <strong>{formatINR(p.floor)}</strong></span><b>Active</b></article>)}</div></section> }

function OrderSuccess({ deal, orderNumber, onShop }: { deal: Deal | null; orderNumber: string; onShop: () => void }) { const saving = deal ? deal.product.price - deal.price : 0; return <section className="page success"><div className="success-mark">✓</div><p className="eyebrow"><i />Order confirmed</p><h1>Your deal is locked.</h1><p className="description">Order {orderNumber} is confirmed. We’ll send your delivery details shortly.</p><div className="success-price"><span>Negotiated price</span><strong>{deal ? formatINR(deal.price) : "₹0"}</strong><em>You saved {formatINR(saving)}</em></div><div className="success-actions"><button className="button button-primary">Track order ↗</button><button className="button button-secondary" onClick={onShop}>Continue shopping</button></div></section> }

function Deals({ onChoose }: { onChoose: (p: Product, next?: View) => void }) { return <section className="page deals"><p className="eyebrow"><i />Negotiated now</p><h1>Offers worth<br /><span>talking about.</span></h1><p className="description">The price you see is only where the conversation starts.</p><h2 className="subhead">Hot deals</h2><div className="deal-grid">{products.slice(0, 3).map((p, index) => <article key={p.id}><img src={p.image} alt="" /><div><p>Recent negotiated deal</p><h3>{p.name}</h3><s>{formatINR(p.price)}</s><strong>{formatINR(p.price - (1200 + index * 300))}</strong><em>Save {formatINR(1200 + index * 300)}</em><button onClick={() => onChoose(p, "negotiate")}>Get my price ↗</button></div></article>)}</div><div className="deal-notice"><span>✦</span><p>Deals are created from real seller-approved negotiations. No artificial countdowns, no pressure.</p></div></section> }

function HowItWorks({ onStart }: { onStart: () => void }) { const workflow = ["Choose a product", "Make an offer", "AI negotiates", "Reach a deal", "Buy at your price"]; return <section className="page how-page"><p className="eyebrow"><i />How it works</p><h1>A better price starts<br />with <span>one sentence.</span></h1><div className="workflow">{workflow.map((item, i) => <article key={item}><span>0{i + 1}</span><h2>{item}</h2><p>{["Browse the marketplace and find something you love.", "Speak naturally or type the price you have in mind.", "Marchander understands your offer and proposes a seller-approved response.", "Counter, accept, or walk away—every option stays clear.", "Your agreed price moves to your bag, ready for checkout."][i]}</p></article>)}</div><section className="ai-explainer"><p className="eyebrow"><i />Behind the conversation</p><h2>How Marchander AI negotiates.</h2><div className="ai-flow">{["Voice input", "Speech to text", "Offer extraction", "Negotiation engine", "Counter offer", "Voice response"].map((item) => <span key={item}>{item}</span>)}</div><p>It understands an offer, follows seller-defined constraints, and makes each step visible. You always see the offers exchanged and can reject a deal at any time.</p><button className="button button-primary" onClick={onStart}>Start negotiating ↗</button></section></section> }

function Dashboard({ saved, onHistory, onSettings }: { saved: string[]; onHistory: () => void; onSettings: () => void }) { return <section className="page dashboard"><p className="eyebrow"><i />Your space</p><h1>Good to see you, Ankan.</h1><div className="metrics user-metrics"><article><span>04</span><p>Total orders</p><em>Across all time</em></article><article><span>₹8.4K</span><p>Total saved</p><em>Through negotiation</em></article><article><span>02</span><p>Active deals</p><em>Waiting for you</em></article><article><span>11</span><p>Negotiations</p><em>Offers made</em></article></div><div className="dashboard-grid"><section className="recent"><div><h2>Recent negotiations</h2><button onClick={onHistory}>View all ↗</button></div>{products.slice(0, 3).map((p, i) => <article key={p.id}><img src={p.image} alt="" /><span>{p.name}</span><span>{formatINR(p.price)} → <strong>{formatINR(p.price - (1000 + i * 400))}</strong></span><em>Deal completed</em></article>)}</section><section className="savings"><h2>Money saved through negotiation</h2><strong>₹8,420</strong><div className="chart"><i style={{ height: "25%" }} /><i style={{ height: "44%" }} /><i style={{ height: "38%" }} /><i style={{ height: "72%" }} /><i style={{ height: "57%" }} /><i style={{ height: "93%" }} /></div><p>Last six successful offers</p></section></div><section className="wishlist"><div><h2>Wishlist</h2><button onClick={onSettings}>Manage preferences ↗</button></div>{saved.length ? <p>{saved.length} saved item{saved.length > 1 ? "s" : ""} ready for an offer.</p> : <p>Save products you like and return when you’re ready to negotiate.</p>}</section></section> }

function History({ onNegotiate }: { onNegotiate: () => void }) { return <section className="page history"><p className="eyebrow"><i />Negotiation history</p><h1>Every offer,<br /><span>kept clear.</span></h1><div className="history-list">{products.slice(0, 3).map((p, i) => <article key={p.id}><img src={p.image} alt="" /><div><h2>{p.name}</h2><p>{formatINR(p.price)} <b>↓</b> {formatINR(p.price - (900 + i * 400))} <b>✓</b></p><em>Saved {formatINR(900 + i * 400)} · Deal completed</em></div><button onClick={onNegotiate}>View conversation ↗</button></article>)}</div></section> }

function Settings() { return <section className="page settings"><p className="eyebrow"><i />Profile & settings</p><h1>Make it yours.</h1><div className="settings-grid">{[["Account", ["Name", "Email", "Phone"]], ["Voice settings", ["Preferred language", "Marchander voice", "Speech speed"]], ["Shopping preferences", ["Preferred categories", "Deal notifications", "Wishlist updates"]], ["Security", ["Password", "Login sessions", "Account security"]]].map(([title, rows]) => <section key={title as string}><h2>{title as string}</h2>{(rows as string[]).map((row) => <button key={row}>{row}<span>›</span></button>)}</section>)}</div></section> }

function About({ onHow }: { onHow: () => void }) { return <section className="page about"><p className="eyebrow"><i />About Marchander</p><h1>Make online shopping<br />feel like <span>a conversation.</span></h1><div className="about-copy"><section><h2>The problem</h2><p>E-commerce made prices fixed and transactions fast, but it removed the human conversation that helps people find a deal that works.</p></section><section><h2>Our mission</h2><p>Make negotiation a native feature of digital commerce—clear for shoppers, controllable for sellers, and simple for everyone.</p></section><section><h2>Built with care</h2><p>Voice, AI, and a negotiation engine work together without hiding the price, the choice, or the final agreement.</p></section></div><section className="trust-block"><h2>Negotiation you can see.</h2><p>AI operates within seller-defined constraints. Every offer remains visible. You see the final price before you buy, and you can say no at any time.</p><button className="button button-primary" onClick={onHow}>See how it works ↗</button></section></section> }
